export const PROJECTS = [
    {
        imageFilename: "graph1.png",
        title: "Dinoflagellates alter carbon and nutrient metabolism across biogeochemical gradients",
        text: "A natural geochemical gradient exists in the central Pacific Ocean in which tropical, oligotrophic regions are low in nitrogen (N), while the equatorial upwelling region is N-rich and comparatively low in dissolved iron (Fe). It is unknown how unicellular eukaryotes (protists) across this transition zone differ in nutrient utilization, growth strategies, and contributions to carbon export. Using a combined ‘omic set including metatranscriptomes, metaproteomes, and 18S metabarcoding data along with geochemical measurements, we have characterized metabolic profiles spanning the euphotic to mesopelagic zones. Our findings suggest that dinoflagellates are relatively abundant throughout the water column (to ~800m) and demonstrate a tremendous amount of plasticity when adapting to various chemical environments. Although diatoms are typically regarded as key eukaryotes driving the biological carbon pump in the equatorial Pacific, our results suggest that the dinoflagellates play a previously unrecognized role in the ecosystem due to their broad extent and diverse metabolic strategies.",
        collaborators: "Matt McIlvin (WHOI), Dawn Moran (WHOI), Nick Hawco (WHOI/USC), Noelle Held (WHOI), Jaci Saunders (WHOI), Michael Brosnahan (WHOI), Jack DiTullio (C. Charleston), Carl Lamborg (UCSC), John McCrow (JCVI), Chris Dupont (JCVI), Andrew Allen (JCVI), Mak Saito (WHOI)."
    },
    {
        imageFilename: "heatmap.png",
        title: "Hydrothermal metal input near the Tongan plateau of the tropical South Pacific",
        text: "It is presently unclear whether diverse phytoplankton replace metalloproteins containing trace metals in low supply with ones more abundant in the environment. In the tropical Atlantic, trace metal supplies vary annually with higher inputs during the summer in the form of aerosols derived from the Saharan desert plume (Arimoto et al., 1995). We are examining the relationships among iron and cobalt availability, metalloprotein abundance patterns, and biomarkers of nutritional status in the tropical Atlantic Ocean to better discern the influence of seasonally variable trace metal availability on eukaryotic phytoplankton metal metabolism. During February-March 2018, we performed shipboard mesocosm incubation experiments at three locations in the tropical Atlantic: Mauritantian Upwelling Zone (MUZ) off the coast of Cape Verde, the equatorial Atlantic, and river plume (RP)-influenced seawater off the coast of Venezuela. Eukaryotic phytoplankton blooms were induced by adding macronutrients and metals to 10 L of seawater. Metatranscriptomic and metaproteomic analyses will be used to determine which metals may have been limiting to phytoplankton growth at this site. At the ARP site, we fortuitously sampled during a diatom-diazotroph association (DDA) bloom, a symbiosis in which host diatoms contain endosymbiotic nitrogen-fixing (diazotrophic) cyanobacteria as a source of nitrogen in this typically nitrate–limited system. We plan to explore how diatoms and endosymbiotic diazotrophs restructure their nutrient acquisition or assimilation pathways and symbiotic relationship as a function of increased external nutrient supplies.",
        collaborators: "Dawn Moran (WHOI), Matt McIlvin (WHOI), Andrea Caputo (Stockholm U), Jeff Morris (UAB), Eric Webb (USC), Rachel Foster (Stockholm U), Dave Hutchins (USC), Andrew Allen (JCVI), Mak Saito (WHOI)."
    }
]