export const RESEARCH = [
    {
        imageFilename: "ironvit2.png",
        title: "Iron and vitamin interactions in diatoms",
        text: "Trace metals (such as iron) and biologically-synthesized compounds (such as B-vitamins) play critical roles in regulating marine microorganism growth and composition. Unfortunately, only some microorganisms in the surface ocean are capable of producing these important B-vitamins, while others cannot and depend on others for their supply. Therefore the external factors influencing B-vitamin production, such as iron status, alter the extent to which B-vitamins are available in surface waters. Laboratory culture experiments with targeted gene expression analyses in diatoms indicate changes in iron bioavailability influence B7 (biotin) synthesis, but not B12 (cobalamin)-sensitive machinery. However, molecular indications of B12 stress are observed in certain members of natural diatom assemblages in the Northeast Pacific Ocean following iron enrichment, as determined through community-wide bioinformatic analyses. This is likely a result of B12 consumption by blooming taxa offsetting microbial B12 production. As a result of altered vitamin levels following natural or artificial iron fertilization, phytoplankton may experience changes in community composition, potentially causing shifts in biogeochemical cycling patterns. This is important because a seemingly minor physiological characteristic, such as the thickness of a diatom’s silica shell, can substantially influence the efficiency of the biological carbon pump, with heavier, thicker cells transporting more carbon to the deep ocean!",
        biblio: "Cohen NR, Ellis KA, Burns W, Lampe RH, Schuback N, Johnson Z, Sañudo-Wilhelmy S, Marchetti A. Iron and vitamin interactions in marine diatom isolates and natural assemblages of the Northeast Pacific Ocean (2017) Limnology and Oceanography 62: 2076-2096. doi:10.1002/lno.10552"
    },
    {
        title: "Ferritin functional roles in diatoms",
        text: "A large amount of genetic diversity is contained within the group of phytoplankton that responds to iron addition events very quickly in the surface ocean: the diatoms. Diatom species often vary in their physiological response to iron, with large blooms of primarily pennate diatoms blooming when iron is added to previously iron-limited waters. The ability of pennate diatoms to proliferate following iron addition has been partly attributed to their ability to store iron through the iron storage protein, ferritin. However, transcriptomic sequencing of diatoms indicates that some centric diatoms also possess ferritin proteins. Using a combination of physiological and targeted gene expression approaches, we examined the iron storage capacities and associated ferritin gene expression among diverse diatoms grown under a range of iron levels. This work explores how a single protein may be used for multiple purposes among diatoms, likely depending on the environment in which each taxon is adapted.",
        biblio: "Cohen NR, Mann, E, Stemple B, Raushenberg S, Jacquot J, Moreno C, Sunda W.G, Twining B.S, Marchetti A. Iron storage capacities and associated ferritin gene expression among marine diatoms. (2018) Limnology & Oceanography 63: 1677-1691 doi:10.1002/lno.10800"
    }
]